<div class="container-fluid">
    <h4 class="margin-top-20">Danh sách đơn hàng</h4>
    <div class="alert alert-success alert-dismissable fade show">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <?php
        if (!empty($data['msg'])) {
            $tong = count($data['data']);
            echo '<b>' . $data['msg'] . " <strong>($tong)</strong></b>";
        }
        ?>
    </div>
    <div class="table-responsive">
        <table class="table table-bordered table-hover">
            <thead class="thead-dark">
            <th>ID</th>
            <th>Ngày đặt</th>
            <th>Trạng thái</th>
            <th>Ngày cập nhật</th>
            <th>Thông tin khách hàng</th>
            <th>Ghi chú</th>
            <th>Sửa</th>
            <th>Chi tiết</th>
            </thead>
            <?php
            foreach ($data['data'] as $row) {
                if(isset($row['trang_thai'])){
                    if($row['trang_thai'] == 0){
                        $trangthai = 'Chưa xử lý';
                    }
                    else
                        if($row['trang_thai'] == 1){
                            $trangthai = 'Đã xử lý';
                        }
                        else
                            if($row['trang_thai'] == -1){
                                $trangthai = 'Đã hủy';
                            }}
                $link = '?controller=admin-product&action=update-order&id=' . $row['id'];
                $link_view = '?controller=admin-product&action=view-order&id=' . $row['id'];?>
                <tr>
                    <td><?php echo $row['id']; ?></td>
                    <td><?php echo $row['ngay_gio_dat']; ?></td>
                    <td><?php echo $trangthai; ?></td>
                    <td><?php echo $row['ngay_cap_nhat']; ?></td>
                    <td>
                        <span>Họ tên: <?php echo $row['ho_ten']; ?></span><br>
                        <span>Địa chỉ: <?php echo $row['dia_chi']; ?></span><br>
                        <span>Điện thoại: <?php echo $row['dien_thoai']; ?></span><br>
                        <span>Email: <?php echo $row['email']; ?></span>
                    </td>
                    <td><?php echo $row['ghi_chu']; ?></td>
                    <td><a href="<?php echo $link; ?>">Sửa</a></td>
                    <td><a href="<?php echo $link_view; ?>">Xem</a></td>
                </tr>
                <?php
            }
            ?>
        </table>
    </div>
    <?php
    if ($data['total_pages'] > 1) {
        $previous = isset($_GET['page'])?$_GET['page']-1:1;
        $next = isset($_GET['page'])?$_GET['page']+1:2;
        if(@$_GET['page']==1 || !isset($_GET['page'])){
            $disabled1 = 'disabled';
        }
        else{
            $disabled1 = '';
        }
        if(@$_GET['page']==$data['total_pages']){
            $disabled2 = 'disabled';
        }
        else{
            $disabled2 = '';
        }
        ?>
        <ul class="pagination">
            <li class="page-item <?php echo $disabled1;?>"><a class="page-link" href="?controller=admin-product&action=list-producer&page=<?php echo $previous;?>"><i class="fa fa-angle-double-left"></i></a></li>
            <?php
            for ($page = 1; $page <= $data['total_pages']; $page++) {
                if(@$_GET['page']==$page){
                    $active = 'active';
                }
                else{
                    $active = '';
                }
                echo '<li class="page-item '.$active.'"><a class="page-link" href="?controller=admin-product&action=list-producer&page=' . $page . '">' . $page . '</a></li>';
            }
            ?>
            <li class="page-item <?php echo $disabled2;?>"><a class="page-link" href="?controller=admin-product&action=list-producer&page=<?php echo $next; ?>"><i class="fa fa-angle-double-right"></i></a></li>
        </ul>
        <?php
    }
    ?>
</div>