<div class="container-fluid">
    <h4 class="margin-top-20">Danh sách tài khoản</h4>
    <div class="alert alert-success alert-dismissable fade show">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <?php
        if (!empty($data['msg'])) {
            echo '<b>' . $data['msg'] . "</b>";
        }
        ?>
    </div>
    <div class="table-responsive">
        <table class="table table-bordered table-hover">
            <thead class="thead-dark">
            <tr>
                <th>STT</th>
                <th>ID</th>
                <th>Tên đăng nhập</th>
                <th>Email</th>
                <th>Tên nhóm</th>
                <th>Xóa</th>
            </tr>
            </thead>
            <tbody>
            <?php
            $stt = 1;

            foreach ($data['data'] as $value) {
                $link_edit   = "?controller=admin-user&action=edit&id=" . $value['id'];
                $link_delete = "?controller=admin-user&action=delete&id=" . $value['id'];
                ?>
                <tr>
                    <td><?php echo $stt; ?></td>
                    <td><?php echo $value['id'] ?></td>
                    <td><a href="<?php echo $link_edit; ?>"><?php echo $value['ten_dang_nhap'] ?></a></td>
                    <td><?php echo $value['email'] ?></td>
                    <td><?php echo $value['ten_nhom'] ?></td>
                    <td><a href="<?php echo $link_delete; ?>">Xóa</a></td>
                </tr>
                <?php $stt++;
            } ?>
            </tbody>
        </table>
    </div>
    <?php
    if ($data['total_pages'] > 1) {
        $previous = isset($_GET['page']) ? $_GET['page'] - 1 : 1;
        $next     = isset($_GET['page']) ? $_GET['page'] + 1 : 2;
        if (@$_GET['page'] == 1 || !isset($_GET['page'])) {
            $disabled1 = 'disabled';
        } else {
            $disabled1 = '';
        }
        if (@$_GET['page'] == $data['total_pages']) {
            $disabled2 = 'disabled';
        } else {
            $disabled2 = '';
        }
        ?>
        <ul class="pagination">
            <li class="page-item <?php echo $disabled1; ?>"><a class="page-link"
                                                               href="?controller=admin-group&action=list&page=<?php echo $previous; ?>"><i
                            class="fa fa-angle-double-left"></i></a></li>
            <?php
            for ($page = 1; $page <= $data['total_pages']; $page++) {
                if (@$_GET['page'] == $page) {
                    $active = 'active';
                } else {
                    $active = '';
                }
                echo '<li class="page-item ' . $active . '"><a class="page-link" href="?controller=admin-user&action=list&page=' . $page . '">' . $page . '</a></li>';
            }
            ?>
            <li class="page-item <?php echo $disabled2; ?>"><a class="page-link"
                                                               href="?controller=admin-group&action=list&page=<?php echo $next; ?>"><i
                            class="fa fa-angle-double-right"></i></a></li>
        </ul>
        <?php
    }
    ?>
    <a href="?controller=admin-user&action=add">Thêm tài khoản</a>
</div>