<div class="container-fluid">
    <h4 class="margin-top-20 margin-bottom-30">Thêm mới chức năng</h4>
<?php
if(!empty($data['msg'])){?>
    <div class="alert alert-success alert-dismissable fade show">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <?php
    echo '<b>'.$data['msg']."</b></div>";
}
?>
<form action="" method="post">
    <div class="form-group">
        <label for="text">Tên chức năng</label>
        <input class="form-control" type="text" name="txt_ten_chuc_nang">
    </div>
    <div class="form-group">
        <label for="text">Link</label>
        <input class="form-control" type="text" name="txt_link">
    </div>
        <input type="submit" value="Thêm mới" name="btnSave" class="btn btn-primary">
</form>
<a href="?controller=admin-group&action=list-func">Danh sách chức năng</a>