
<div class="container-fluid">
<div class="alert alert-danger margin-top-20">
    <strong>Xóa chức năng: </strong> <?php  $chuc_nang = isset($data['data']['ten_chuc_nang'])?$data['data']['ten_chuc_nang']:"Không tồn tại chức năng";
    echo $chuc_nang; ?>
</div>
<?php
if(!empty($data['msg'])){?>
<div class="alert alert-success alert-dismissable fade show">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <?php
    echo '<b>'.$data['msg'].'</b></div>';
    }
    ?>
    <div class="alert alert-warning">
        <strong>Bạn có chắc chắn muốn xóa không?</strong>
        <form action="" method="post" class="form-inline">
            <div class="form-group"></div>
            <input type="hidden" name="id_func" value="<?php echo $data['data']['id'];?>">
            <input class="btn btn-info" type="submit" value="Đồng ý xóa" name="btnDelete">
        </form>
    </div>
</div>