<div class="container-fluid">
    <h4 class="margin-top-20">Sửa chức năng</h4>
<?php
if(!empty($data['msg'])){
    ?>
    <div class="alert alert-success alert-dismissable fade show">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <?php

    echo '<b>'.$data['msg']."</b></div>";
}
?>
<form action="" method="post">
    <div class="form-group">
        <label for="text">Tên chức năng</label>
    <input type="text" class="form-control" name="txt_ten_chuc_nang" value="<?php echo $data['data']['ten_chuc_nang']; ?>">
        <label for="text">Link</label>
    <input type="text" class="form-control" name="txt_link" value="<?php echo $data['data']['link']; ?>">
    </div>
    <input type="submit" class="btn btn-info" value="Sửa chức năng" name="btnSave">
</form>
    </div>