<div class="container-fluid">
    <h4 class="margin-top-20">Sửa tài khoản</h4>
    <?php
    if (!empty($data['msg'])) {?>
        <div class="alert alert-success alert-dismissable fade show">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            <?php $dem = count($data['msg']);  foreach ($data['msg'] as $key => $msg) {
                if($key==0) {
                    echo '<b>' . $msg . ' <span class="text-danger" data-toggle="collapse" data-target="#xemthem">Xem thêm...</span></b><br><span id="xemthem" class="collapse">';
                }
                else
                    echo '<b >' . $msg . '</b><br>';
                if($key == $dem-1){
                    echo '<b>' . $msg . '</b><br></span>';
                }
            }
            ?>
        </div>
        <?php
    }
    ?>
        <form action="" method="post">
            <div class="form-group">
                <label for="text">Nhóm tài khoản: <?php echo $data['info']['ten_nhom']; ?></label><br>
                <label for="text">Chức năng:</label><br>
                <?php
                foreach ($data['list_func'] as $row){
                    $id_chuc_nang = $row['id'];
                    $ten = $row['ten_chuc_nang'];
                    $link = $row['link'];

                    $check = '';
                    foreach ($data['list_pms'] as $pms){
                        if($pms['id_chuc_nang'] ==$id_chuc_nang )
                        {
                            $check = ' checked ';
                            break;
                        }
                    }

                    echo "<div class=\"form-check\"><label class=\"form-check-label\"><input $check class=\"form-check-input\" type='checkbox' name='cn_$id_chuc_nang'> $ten ($link) <br></label></div>";

                }
                ?>
            </div>
            <input type="submit" value="Cập nhật" name="btnSave" class="btn btn-primary">
        </form>
    </div>