<div class="container-fluid">
    <h4 class="margin-top-20">Danh sách chức năng</h4>
    <div class="alert alert-success alert-dismissable fade show">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <?php
        if (!empty($data['msg'])) {
            $tong = count($data['data']);
            echo '<b>' . $data['msg'] . " <strong>($tong)</strong></b>";
        }
        ?>
    </div>
    <div class="table-responsive">
        <table class="table table-bordered table-hover">
            <thead class="thead-dark">
            <th>ID</th>
            <th>Tên chức năng</th>
            <th>Link</th>
            <th>Xóa</th>
            </thead>
            <tbody>
            <?php foreach ($data['data'] as $row) {
                ?>
                <tr>
                    <td><?php echo $row['id']; ?></td>
                    <td>
                        <a href="?controller=admin-group&action=edit-func&id=<?php echo $row['id']; ?>"><?php echo $row['ten_chuc_nang']; ?></a>
                    </td>
                    <td><?php echo $row['link']; ?></td>
                    <td><a href="?controller=admin-group&action=delete-func&id=<?php echo $row['id']; ?>">Xóa</a></td>
                </tr>
            <?php } ?>
            </tbody>
        </table>
    </div>
    <?php
    if ($data['total_pages'] > 1) {
        $previous = isset($_GET['page']) ? $_GET['page'] - 1 : 1;
        $next     = isset($_GET['page']) ? $_GET['page'] + 1 : 2;
        if (@$_GET['page'] == 1 || !isset($_GET['page'])) {
            $disabled1 = 'disabled';
        } else {
            $disabled1 = '';
        }
        if (@$_GET['page'] == $data['total_pages']) {
            $disabled2 = 'disabled';
        } else {
            $disabled2 = '';
        }
        ?>
        <ul class="pagination">
            <li class="page-item <?php echo $disabled1; ?>"><a class="page-link"
                                                               href="?controller=admin-group&action=list&page=<?php echo $previous; ?>"><i
                            class="fa fa-angle-double-left"></i></a></li>
            <?php
            for ($page = 1; $page <= $data['total_pages']; $page++) {
                if (@$_GET['page'] == $page) {
                    $active = 'active';
                } else {
                    $active = '';
                }
                echo '<li class="page-item ' . $active . '"><a class="page-link" href="?controller=admin-group&action=list-func&page=' . $page . '">' . $page . '</a></li>';
            }
            ?>
            <li class="page-item <?php echo $disabled2; ?>"><a class="page-link"
                                                               href="?controller=admin-group&action=list&page=<?php echo $next; ?>"><i
                            class="fa fa-angle-double-right"></i></a></li>
        </ul>
        <?php
    }
    ?>
    <a href="?controller=admin-group&action=add-func">Thêm chức năng mới</a>
</div>