<div class="container-fluid">
    <h4 class="margin-top-20">Danh sách bài viết</h4>
    <div class="alert alert-success alert-dismissable fade show">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <?php
        if (!empty($data['msg'])) {
            $tong = count($data['data']);
            echo '<b>' . $data['msg'] . " ($tong)</b>";
        }
        ?>
    </div>
    <div class="table-responsive">
        <table class="table table-bordered table-hover">
            <thead class="thead-dark">
             <th>ID</th>
            <th>Tiêu đề</th>
            <th>Nội dung</th>
            <th>Ngày đăng</th>
            <th>Người đăng</th>
            <th>Danh mục</th>
            <th>Ảnh</th>
            <th>Xem</th>
            <th>Xóa</th>
            </thead>
            <?php
            foreach ($data['data'] as $row) {
            $link        = '?controller=admin-article&action=edit-article&id=' . $row['id'];
            $link_delete = '?controller=admin-article&action=delete-article&id=' . $row['id'];
            $link_view = '?controller=article&action=detail&id=' . $row['id'];
            ?>
            <tbody>
            <tr>
                <td><?php echo $row['id']; ?></td>
                <td><a href="<?php echo $link ?>"><?php echo $row['tieu_de']; ?></a></td>
                <td><?php
                    $count_content = strlen($row['noi_dung']);
                    if($count_content > 50){
                        $short_str = substr($row['noi_dung'],0,50);
                        $short_str .='...';
                    }
                    else
                        $short_str = $row['noi_dung'];
                    echo $short_str; ?></td>
                <td><?php echo $row['ngay_dang']; ?></td>
                <td><?php echo $row['ten_dang_nhap']; ?></td>
                <td><?php echo $row['ten_danh_muc']; ?></td>
                <td><img style="max-width: 100px !important;" class="img-fluid" src=".<?php echo _app_path_images_public.'/images-article/'.$row['hinh_anh']; ?>"</td>
                <td><a href="<?php echo $link_delete ?>">Xóa</a></td>
                <td><a href="<?php echo $link_view ?>">Xem</a></td>
            </tr>
            <?php } ?>
            </tbody>
        </table>
    </div>
    <?php
    if ($data['total_pages'] > 1) {
        $previous = isset($_GET['page']) ? $_GET['page'] - 1 : 1;
        $next     = isset($_GET['page']) ? $_GET['page'] + 1 : 2;
        if (@$_GET['page'] == 1 || !isset($_GET['page'])) {
            $disabled1 = 'disabled';
        } else {
            $disabled1 = '';
        }
        if (@$_GET['page'] == $data['total_pages']) {
            $disabled2 = 'disabled';
        } else {
            $disabled2 = '';
        }
        ?>
        <ul class="pagination">
            <li class="page-item <?php echo $disabled1; ?>"><a class="page-link"
                                                               href="?controller=admin-article&action=list-article&page=<?php echo $previous; ?>"><i
                        class="fa fa-angle-double-left"></i></a></li>
            <?php
            for ($page = 1; $page <= $data['total_pages']; $page++) {
                if (@$_GET['page'] == $page) {
                    $active = 'active';
                } else {
                    $active = '';
                }
                echo '<li class="page-item ' . $active . '"><a class="page-link" href="?controller=admin-article&action=list-article&page=' . $page . '">' . $page . '</a></li>';
            }
            ?>
            <li class="page-item <?php echo $disabled2; ?>"><a class="page-link"
                                                               href="?controller=admin-article&action=list-article&page=<?php echo $next; ?>"><i
                        class="fa fa-angle-double-right"></i></a></li>
        </ul>
        <?php
    }
    ?>
    <a href="?controller=admin-article&action=add-article">Thêm bài viết mới</a>
</div>