<?php
if (@$data['total_pages']['product'] > 1) {
    $previous = isset($_GET['page']) ? $_GET['page'] - 1 : 1;
    $next     = isset($_GET['page']) ? $_GET['page'] + 1 : 2;
    if (@$_GET['page'] == 1 || !isset($_GET['page'])) {
        $disabled1 = 'disabled';
    } else {
        $disabled1 = '';
    }
    if (@$_GET['page'] == $data['total_pages']['product']) {
        $disabled2 = 'disabled';
    } else {
        $disabled2 = '';
    }
    ?>
    <ul class="pagination">
        <li class="page-item <?php echo $disabled1; ?>"><a class="page-link"
                                                           href="?page=<?php echo $previous; ?>"><i
                    class="fa fa-angle-double-left"></i></a></li>
        <?php
        for ($page = 1; $page <= $data['total_pages']['product']; $page++) {
            if (@$_GET['page'] == $page) {
                $active = 'active';
            } else {
                $active = '';
            }
            echo '<li class="page-item ' . $active . '"><a class="page-link" href="?page=' . $page . '">' . $page . '</a></li>';
        }
        ?>
        <li class="page-item <?php echo $disabled2; ?>"><a class="page-link"
                                                           href="?page=<?php echo $next; ?>"><i
                    class="fa fa-angle-double-right"></i></a></li>
    </ul>
    <?php
}
?>