<?php
$template_url ='public/backend/';
?>
<!DOCTYPE html>
<html>
<head>
    <title>Quản Trị Website</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="<?php echo $template_url;?>css/style.css">
    <link rel="stylesheet" href="<?php echo $template_url;?>css/bootstrap.min.css">
    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
    <link rel="stylesheet" href="<?php echo $template_url;?>css/sb-admin.css">
</head>
<body class="fixed-nav sticky-footer bg-dark" id="page-top">
<!-- Navigation-->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top" id="mainNav">
    <a class="navbar-brand" href="?controller=admin-group">Quản trị website</a>
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav navbar-sidenav" id="exampleAccordion">
            <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Dashboard">
                <a class="nav-link" href="?controller=admin-group">
                    <i class="fa fa-fw fa-dashboard"></i>
                    <span class="nav-link-text">Home</span>
                </a>
            </li>
            <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Quản lý tài khoản">
                <a class="nav-link nav-link-collapse collapsed" data-toggle="collapse" href="#collapseUsers" data-parent="#exampleAccordion">
                    <i class="fa fa-user"></i>
                    <span class="nav-link-text">Quản lý tài khoản</span>
                </a>
                <ul class="sidenav-second-level collapse" id="collapseUsers">
                    <li><a href="?controller=admin-group&action=list">Nhóm Tài khoản</a> </li>
                    <li><a href="?controller=admin-user&action=list">Tài khoản</a></li>
                    <li><a href="?controller=admin-group&action=list-func">Chức năng</a></li>
                </ul>
            </li>
            <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Quản lý sản phẩm">
                <a class="nav-link nav-link-collapse collapsed" data-toggle="collapse" href="#collapseProducts" data-parent="#exampleAccordion">
                    <i class="fa fa-shopping-cart"></i>
                    <span class="nav-link-text">Quản lý sản phẩm</span>
                </a>
                <ul class="sidenav-second-level collapse" id="collapseProducts">
                    <li><a href="?controller=admin-product&action=list-category">Danh Mục Sản phẩm</a></li>
                    <li><a href="?controller=admin-product&action=list-producer">Hãng sản xuất</a></li>
                    <li><a href="?controller=admin-product&action=list">Sản phẩm</a></li>
                    <li><a href="?controller=admin-product&action=list-order">Đơn hàng</a></li>
                </ul>
            </li>
            <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Quản lý bài viết">
                <a class="nav-link nav-link-collapse collapsed" data-toggle="collapse" href="#collapsePost" data-parent="#exampleAccordion">
                    <i class="fa fa-fw fa-file"></i>
                    <span class="nav-link-text">Quản lý bài viết</span>
                </a>
                <ul class="sidenav-second-level collapse" id="collapsePost">
                    <li><a href="?controller=admin-article&action=list-category">Danh mục bài viết</a></li>
                    <li><a href="?controller=admin-article&action=list-article">Danh sách bài viết</a></li>
                </ul>
            </li>
            <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Quản lý liên hệ">
                <a class="nav-link" href="?controller=admin-contact&action=list-contact">
                    <i class="fa fa-phone"></i>
                    <span class="nav-link-text">Quản lý liên hệ</span>
                </a>
            </li>
        </ul>
        <ul class="navbar-nav sidenav-toggler">
            <li class="nav-item">
                <a class="nav-link text-center" id="sidenavToggler">
                    <i class="fa fa-fw fa-angle-left"></i>
                </a>
            </li>
        </ul>
        <ul class="navbar-nav ml-auto">
            <li class="nav-item">
                <span class="text-white" style="display: inline;">Xin chào, <?php echo @$_SESSION['userLogin']['ten_dang_nhap'];?></span><a style="display: inline-block" class="nav-link" data-toggle="modal" data-target="#exampleModal">
                    <i class="fa fa-fw fa-sign-out"></i>Đăng xuất</a>
            </li>
        </ul>
    </div>
</nav>
<div class="content-wrapper">
    <div class="container-fluid">
        <!-- Content-->
        <?php ShowContentAction() ;?>
        <!-- /.container-fluid-->
        <!-- /.content-wrapper-->
        <footer class="sticky-footer">
            <div class="container">
                <div class="text-center">
                    <small>Copyright © Phạm Phương 2017</small>
                </div>
            </div>
        </footer>
        <!-- Scroll to Top Button-->
        <a class="scroll-to-top rounded" href="#page-top">
            <i class="fa fa-angle-up"></i>
        </a>
        <!-- Logout Modal-->
        <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Bạn có muốn tiếp tục đăng xuất</h5>
                        <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">×</span>
                        </button>
                    </div>
                    <div class="modal-body">Chọn "Đăng xuất" nếu bạn muốn tiếp tục...</div>
                    <div class="modal-footer">
                        <button class="btn btn-secondary" type="button" data-dismiss="modal">Hủy</button>
                        <a class="btn btn-primary" href="?controller=index&action=logout">Đăng xuất</a>
                    </div>
                </div>
            </div>
        </div>
        <script src="<?php echo $template_url;?>js/jquery-3.2.1.min.js"></script>
        <script src="<?php echo $template_url;?>js/bootstrap.bundle.min.js"></script>
        <script src="<?php echo $template_url;?>js/sb-admin.min.js"></script>
        <script src="<?php echo $template_url;?>js/popper.min.js"></script>
        <script src="<?php echo $template_url;?>js/bootstrap.min.js"></script>
    </div>
</body>
</html>

