<?php
$template_url ='public/backend/';
?>
<!DOCTYPE html>
<html>
<head>
    <title>Simple Admin template</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="<?php echo $template_url;?>css/style.css">
    <link rel="stylesheet" href="<?php echo $template_url;?>css/bootstrap.min.css">
    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
    <script src="<?php echo $template_url;?>js/jquery-3.2.1.min.js"></script>
    <script src="<?php echo $template_url;?>js/popper.min.js"></script>
    <script src="<?php echo $template_url;?>js/bootstrap.min.js"></script>
</head>
<body>
<div class="container-fluid">
    <nav class="navbar navbar-expand-sm bg-info navbar-dark sticky-top">
        <a class="navbar-brand" href="?controller=admin-group">Quản trị website |</a>
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link text-white" href="<?php echo _base_path; ?>">Trang chủ</a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-white" href="#">Sản phẩm</a>
            </li>
        </ul>
    </nav>

    <div class="row">
        <div class="col-sm-2">
            <div class="bg-dark height-100-bg">
                <ul class="nav flex-column">
                    <li class="nav-item">
                        <a class="nav-link text-white" data-toggle="collapse" data-target="#qltk">Quản lý tài khoản <span style="float: right;"><i class="fa fa-angle-right"></i></span></a>
                        <div class="collapse" id="qltk">
                            <ul class="nav flex-column bg-secondary">
                                <li class="nav-item"><a class="nav-link text-white" href="?controller=admin-group&action=list">Nhóm Tài khoản</a> </li>
                                <li class="nav-item"><a class="nav-link text-white" href="?controller=admin-user&action=list">Tài khoản</a></li>
                                <li class="nav-item"><a class="nav-link text-white" href="?controller=admin-group&action=list-func">Chức năng</a></li>
                            </ul>
                        </div>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link text-white" data-toggle="collapse" data-target="#qlsp">Quản lý sản phẩm <span style="float: right;"><i class="fa fa-angle-right"></i></span></a>
                        <div class="collapse" id="qlsp">
                            <ul class="nav flex-column bg-secondary">
                                <li class="nav-item"><a class="nav-link text-white" href="?controller=admin-product&action=list-category">Danh Mục Sản phẩm</a></li>
                                <li class="nav-item"><a class="nav-link text-white" href="?controller=admin-product&action=list-producer">Hãng sản xuất</a></li>
                                <li class="nav-item"><a class="nav-link text-white" href="?controller=admin-product&action=list">Sản phẩm</a></li>
                                <li class="nav-item"><a class="nav-link text-white" href="?controller=admin-product&action=list-order">Đơn hàng</a></li>
                            </ul>
                        </div>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-white" data-toggle="collapse" data-target="#qlbv">Quản lý bài viết <span style="float: right;"><i class="fa fa-angle-right"></i></span></a>
                        <div class="collapse" id="qlbv">
                            <ul class="nav flex-column bg-secondary">
                                <li class="nav-item"><a class="nav-link text-white" href="?controller=admin-article&action=list-category">Danh mục bài viết</a></li>
                                <li class="nav-item"><a class="nav-link text-white" href="?controller=admin-article&action=list-article">Danh sách bài viết</a></li>
                            </ul>
                        </div>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-white" href="?controller=admin-contact&action=list-contact">Quản lý liên hệ <span style="float: right;"><i class="fa fa-angle-right"></i></span></a>
                    </li>
                </ul>
            </div>
        </div>
        <div class="col-sm-10">
            <?php ShowContentAction() ;?>
            <footer>
                <div class="bg-info padding-30 margin-top-20">
                    <h6 class="text-white font-italic text-center">Copyright @ 2017 BY Phạm Phương</h6>
                </div>
            </footer>
        </div>
    </div>
</div>
</body>
</html>

