<?php
//$template_url = 'public/backend/';
//?>
<!DOCTYPE html>
<html>
<head>
    <title>Đồ Uống Online</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta charset="utf-8">
    <link rel="stylesheet" href="<?php echo template_url; ?>css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="<?php echo template_url; ?>css/style.css">
    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
    <!--    <script src="--><?php //echo template_url; ?><!--js/main.js"></script>-->
</head>
<body>
<header id="header" class="">
    <div class="container">
        <div class="row">
            <div class="col-md-4 col-sm-4">
                <a class="navbar-brand logo" href="index.php"><img style="width:150px;height:60px;"
                                                                   src="<?php echo template_url . 'images/logo.png' ?>"
                                                                   alt=""></a>
            </div>
            <div class="col-md-4 col-sm-6">
                <form action="" method="get" class="form-inline search-form">
                    <input class="form-control input-search-edit" id="txt_search" name="txt_search" type="search"
                           placeholder="Tìm kiếm...">
                    <button class="btn btn-info btn-search-edit" id="btnSearch" name="btnSearch" type="button">Tìm
                        kiếm
                    </button>
                </form>
            </div>
            <div class="col-md-4 right-text col-sm-2">
                <span class="cart-login">
                    <?php
                    if (isset($_SESSION['cart'])) {
                        $tong_sp_da_mua = 0;
                        foreach ($_SESSION['cart'] as $id_sp => $value)
                            $tong_sp_da_mua += $value;
                    }
                    ?>
                    <a href="?controller=product&action=view-cart" class="text-info"> <span class="cart1-login"> Giỏ hàng</span><i
                                class="fa fa-shopping-cart cart2-login"
                                aria-hidden="true"></i> <?php if (!empty($tong_sp_da_mua)) { ?><strong
                                class="text-danger">[<?php echo $tong_sp_da_mua; ?>]</strong> Item<?php } ?></a> |
                    <?php if (isset($_SESSION['userLogin'])) {
                        echo '<strong class="text-info"><span class="cart1-login">Xin chào: </span><i class="fa fa-user cart2-login" aria-hidden="true"></i> ' . $_SESSION['userLogin']['ten_dang_nhap'] . '</strong>';
                    } else { ?>
                        <a href="?controller=index&action=login" class="text-info"><span
                                    class="cart1-login">Đăng nhập</span><i class="fa fa-user cart2-login"
                                                                           aria-hidden="true"></i></a>
                    <?php } ?>
        </span>
            </div>
        </div>
    </div>
</header>
<nav class="hide-mobile navbar navbar-expand-sm bg-info sticky-top" style="padding: .2rem 0;" role="navigation">
    <div class="container">
        <ul class="navbar-nav text-uppercase">

            <li class="nav-item">
                <a class="nav-link text-white" href="<?php echo _base_path; ?>">Trang chủ</a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-white" href="#sanpham">Sản phẩm</a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-white" href="?controller=index&action=contact">Gửi liên hệ</a>
            </li>
        </ul>
    </div>
</nav>
<!-- mobile menu -->
<div class="nav-side-menu sticky-top bg-light">
    <div class="brand bg-info">
        <button type="button" data-toggle="modal" data-target="#myModal" style="background: transparent; border:none"><i
                    style="color: #ffffff;font-size:20px;" class="fa fa-search" aria-hidden="true"></i></button>
    </div>
    <i class="fa fa-bars fa-2x toggle-btn" data-toggle="collapse" data-target="#menu-content"></i>
    <div class="menu-list">
        <ul id="menu-content" class="menu-content collapse out text-secondary">
            <li>
                <a href="index.php">
                    <i class="fa fa-home fa-lg"></i> Trang chủ
                </a>
            </li>
            <li>
                <a href="#sanpham">
                    <i class="fa fa-shopping-cart"></i> Sản phẩm
                </a>
            </li>
            <li>
                <a href="?controller=index&action=contact">
                    <i class="fa fa-phone" aria-hidden="true"></i> Liên hệ
                </a>
            </li>
        </ul>
    </div>
</div>
<div class="modal fade" id="myModal">
    <div class="modal-dialog modal-sm">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Tìm kiếm sản phẩm</h4>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>
            <div class="modal-body">
                <form action="" method="get" class="form-inline" style="display: flex;justify-content: center">
                    <input class="form-control search-mobile" id="txt_search2" name="txt_search"
                           type="search" placeholder="Tìm kiếm...">
                    <button class="btn btn-info btn-search-edit" id="btnSearch2" name="btnSearch" type="button">
                        Tìm kiếm
                    </button>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>

        </div>
    </div>
</div>
<!-- end header -->
<!--content-->

<section class="margin-top-20">
    <div class="container">
        <?php
        ShowContentAction(); ?>
    </div>
</section>
<footer>
    <div class="container">
        <div class="bg-info padding-30 margin-top-20">
            <div class="text-center text-white">
                <small>Copyright © Phạm Phương 2017</small>
            </div>
        </div>
    </div>
</footer>
<script src="<?php echo template_url; ?>js/jquery-3.2.1.min.js"></script>
<script src="<?php echo template_url; ?>js/popper.min.js"></script>
<script src="<?php echo template_url; ?>js/bootstrap.min.js"></script>
<script src="<?php echo template_url; ?>js/main.js"></script>
</body>
</html>